[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 5

#[profile.default]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
